/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xss_it_nfx_NfxUtil */

#ifndef _Included_xss_it_nfx_NfxUtil
#define _Included_xss_it_nfx_NfxUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    getNativeHandle
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_xss_it_nfx_NfxUtil_getNativeHandle
  (JNIEnv *, jclass, jobject);

/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    setTitleBarColor
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_xss_it_nfx_NfxUtil_setTitleBarColor
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
