/* DO NOT EDIT THIS FILE - it is machine generated */
#pragma once

#include <jni.h>
/* Header for class xss_it_nfx_NfxUtil */

#ifndef _Included_xss_it_nfx_NfxUtil
#define _Included_xss_it_nfx_NfxUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef xss_it_nfx_NfxUtil_HT_CLIENT
#define xss_it_nfx_NfxUtil_HT_CLIENT 1L
#undef xss_it_nfx_NfxUtil_HT_CAPTION
#define xss_it_nfx_NfxUtil_HT_CAPTION 2L
#undef xss_it_nfx_NfxUtil_HT_SYS_MENU
#define xss_it_nfx_NfxUtil_HT_SYS_MENU 3L
#undef xss_it_nfx_NfxUtil_HT_MIN_BUTTON
#define xss_it_nfx_NfxUtil_HT_MIN_BUTTON 8L
#undef xss_it_nfx_NfxUtil_HT_MAX_BUTTON
#define xss_it_nfx_NfxUtil_HT_MAX_BUTTON 9L
#undef xss_it_nfx_NfxUtil_HT_TOP
#define xss_it_nfx_NfxUtil_HT_TOP 12L
#undef xss_it_nfx_NfxUtil_HT_CLOSE
#define xss_it_nfx_NfxUtil_HT_CLOSE 20L
#undef xss_it_nfx_NfxUtil_DWM_WCP_DEFAULT
#define xss_it_nfx_NfxUtil_DWM_WCP_DEFAULT 0L
#undef xss_it_nfx_NfxUtil_DWM_WCP_DO_NOT_ROUND
#define xss_it_nfx_NfxUtil_DWM_WCP_DO_NOT_ROUND 1L
#undef xss_it_nfx_NfxUtil_DWM_WCP_ROUND
#define xss_it_nfx_NfxUtil_DWM_WCP_ROUND 2L
#undef xss_it_nfx_NfxUtil_DWM_WCP_ROUND_SMALL
#define xss_it_nfx_NfxUtil_DWM_WCP_ROUND_SMALL 3L
/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    getNativeHandle
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_xss_it_nfx_NfxUtil_getNativeHandle
  (JNIEnv *, jclass, jobject);

/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    setTitleBarColor
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_xss_it_nfx_NfxUtil_setTitleBarColor
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    setTextColor
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_xss_it_nfx_NfxUtil_setTextColor
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    hideFromTaskBar
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_xss_it_nfx_NfxUtil_hideFromTaskBar
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    install
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xss_it_nfx_NfxUtil_install
  (JNIEnv *, jclass, jlong);

/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    update
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_xss_it_nfx_NfxUtil_update
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    setCornerPreference
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_xss_it_nfx_NfxUtil_setCornerPreference
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    setBorderColor
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_xss_it_nfx_NfxUtil_setBorderColor
  (JNIEnv *, jobject, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
