/* DO NOT EDIT THIS FILE - it is machine generated */
#pragma once

#include <jni.h>
/* Header for class xss_it_nfx_AbstractNfxUndecoratedWindow */

#ifndef _Included_xss_it_nfx_AbstractNfxUndecoratedWindow
#define _Included_xss_it_nfx_AbstractNfxUndecoratedWindow
#ifdef __cplusplus
extern "C" {
#endif
 /*
  * Class:     xss_it_nfx_AbstractNfxUndecoratedWindow
  * Method:    hideFromTaskBar
  * Signature: (JZ)V
  */
 JNIEXPORT void JNICALL Java_xss_it_nfx_AbstractNfxUndecoratedWindow_hideFromTaskBar
   (JNIEnv *, jobject, jlong, jboolean);

 /*
  * Class:     xss_it_nfx_AbstractNfxUndecoratedWindow
  * Method:    install
  * Signature: (J)V
  */
 JNIEXPORT void JNICALL Java_xss_it_nfx_AbstractNfxUndecoratedWindow_install
   (JNIEnv *, jobject, jlong);

  /*
 * Class:     xss_it_nfx_AbstractNfxUndecoratedWindow
 * Method:    uninstall
 * Signature: (J)V
 */
  JNIEXPORT void JNICALL Java_xss_it_nfx_AbstractNfxUndecoratedWindow_uninstall
    (JNIEnv *, jobject, jlong);

 /*
  * Class:     xss_it_nfx_AbstractNfxUndecoratedWindow
  * Method:    update
  * Signature: (JZZ)V
  */
 JNIEXPORT void JNICALL Java_xss_it_nfx_AbstractNfxUndecoratedWindow_update
   (JNIEnv *, jobject, jlong, jboolean, jboolean);


#ifdef __cplusplus
}
#endif
#endif
