/* DO NOT EDIT THIS FILE - it is machine generated */
#pragma once


#include <jni.h>
/* Header for class xss_it_nfx_NfxUtil */

#ifndef _Included_xss_it_nfx_NfxUtil
#define _Included_xss_it_nfx_NfxUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef xss_it_nfx_NfxUtil_DWM_WCP_DEFAULT
#define xss_it_nfx_NfxUtil_DWM_WCP_DEFAULT 0L
#undef xss_it_nfx_NfxUtil_DWM_WCP_DO_NOT_ROUND
#define xss_it_nfx_NfxUtil_DWM_WCP_DO_NOT_ROUND 1L
#undef xss_it_nfx_NfxUtil_DWM_WCP_ROUND
#define xss_it_nfx_NfxUtil_DWM_WCP_ROUND 2L
#undef xss_it_nfx_NfxUtil_DWM_WCP_ROUND_SMALL
#define xss_it_nfx_NfxUtil_DWM_WCP_ROUND_SMALL 3L
/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    getNativeHandle
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_xss_it_nfx_NfxUtil_getNativeHandle
(JNIEnv *, jclass, jobject);

/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    setTitleBarColor
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_xss_it_nfx_NfxUtil_setTitleBarColor
(JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    setTextColor
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_xss_it_nfx_NfxUtil_setTextColor
(JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    setCornerPreference
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_xss_it_nfx_NfxUtil_setCornerPreference
(JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    setBorderColor
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_xss_it_nfx_NfxUtil_setBorderColor
(JNIEnv *, jobject, jlong, jint, jint, jint);


 /*
 * Class:     xss_it_nfx_NfxUtil
 * Method:    focusWindow
 * Signature: (Ljava/lang/String;)V
 */
 JNIEXPORT void JNICALL Java_xss_it_nfx_NfxUtil_focusWindow
   (JNIEnv *, jclass, jstring);


#ifdef __cplusplus
}
#endif
#endif
